spring.config.import=file:.env[.properties]
spring.profiles.active=${ACTIVE_PROFILE}

spring.application.name=user-service

spring.datasource.hikari.maximum-pool-size=${DB_MAX_POOL_SIZE}
spring.datasource.hikari.minimum-idle=${DB_MIN_IDLE_CONNECTIONS}
spring.datasource.hikari.max-lifetime=${DB_CONNECTION_LIFETIME_MS}
spring.datasource.hikari.connection-timeout=${DB_CONNECTION_TIMEOUT_MS}

spring.task.execution.pool.core-size=${THREAD_CORE_POOL_SIZE}
spring.task.execution.pool.max-size=${THREAD_MAX_POOL_SIZE}
spring.task.execution.pool.queue-capacity=${THREAD_QUEUE_CAPACITY}
spring.task.execution.pool.keep-alive=${THREAD_KEEP_ALIVE_MS}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
