spring.application.name=user-service

# Profile selection (safe default)
spring.profiles.active=${ACTIVE_PROFILE:dev}

server.port=${SERVER_PORT:8081}

# Logging (shared baseline)
logging.file.name=application.log
logging.file.path=logs

logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
